name: Deploy to Server

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              run: |
                  sudo apt-get update
                  sudo apt-get install -y sshpass

            - name: Deploy to server
              run: |
                  sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
                    cd /var/www/spaceflightmechanics.com
                    sh ./scripts/deploy.sh
                  '
